# Generated by Django 5.2.7 on 2025-10-18 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='breed_detection/')),
                ('detected_breed', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence percentage', null=True)),
                ('alternative_breeds', models.JSONField(blank=True, default=list, help_text='List of alternative breeds with confidence')),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('processing_time', models.FloatField(blank=True, help_text='Time taken in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_module.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_diet', models.TextField()),
                ('daily_calories', models.IntegerField(help_text='Recommended daily calories')),
                ('feeding_frequency', models.CharField(max_length=100)),
                ('food_types', models.JSONField(default=list, help_text='List of recommended food types')),
                ('special_considerations', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('health_conditions', models.TextField(blank=True)),
                ('recommended_products', models.JSONField(blank=True, default=list, help_text='List of product IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_recommendations', to='users.petprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disease_detection/')),
                ('disease_type', models.CharField(choices=[('skin', 'Skin Disease'), ('eye', 'Eye Disease'), ('ear', 'Ear Disease'), ('dental', 'Dental Issue'), ('general', 'General Health')], max_length=20)),
                ('detected_disease', models.CharField(blank=True, max_length=200)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('recommendations', models.TextField(blank=True)),
                ('should_see_vet', models.BooleanField(default=False)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_detections', to='users.petprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoEnhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='photo_enhancement/original/')),
                ('enhanced_image', models.ImageField(blank=True, null=True, upload_to='photo_enhancement/enhanced/')),
                ('enhancement_type', models.CharField(choices=[('enhance', 'Quality Enhancement'), ('filter', 'Filter Applied'), ('background', 'Background Removal'), ('colorize', 'Colorization')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Enhancement parameters')),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_enhancements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
