# Generated by Django 5.2.7 on 2026-02-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeddetection',
            name='is_dog',
            field=models.BooleanField(default=True, help_text='Whether a dog was detected'),
        ),
        migrations.AddField(
            model_name='breeddetection',
            name='is_human',
            field=models.BooleanField(default=False, help_text='Whether a human face was detected'),
        ),
    ]
