# Generated by Django 5.2.7 on 2025-11-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_migrate_adoption_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='adoptions',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='store.adoptionlisting'),
        ),
    ]
