# Generated by Django 5.2.7 on 2025-11-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartitem_product_name_cartitem_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='NPR', max_length=10),
        ),
    ]
