# Generated by Django 5.2.7 on 2025-11-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
