# Generated by Django 5.2.7 on 2025-11-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_groupmessage_is_system_message'),
        ('community', '0003_groupmessage'),
    ]

    operations = [
    ]
