# Generated by Django 5.2.7 on 2025-11-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_merge_20251118_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
