# Generated by Django 5.2.7 on 2025-11-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_conversation_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdoptionListing',
        ),
    ]
