# Generated by Django 5.2.7 on 2025-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('vaccination', 'Vaccination Reminder'), ('food_restock', 'Food Restock'), ('vet_checkup', 'Vet Checkup'), ('order', 'Order Update'), ('community', 'Community Activity'), ('message', 'New Message'), ('follow', 'New Follower'), ('event_joined', 'Event Joined'), ('event_starting', 'Event Starting Soon'), ('event_ended', 'Event Ended'), ('system', 'System')], max_length=20),
        ),
    ]
