# Generated by ChatGPT - simple migration for UserOTP
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def create_userotp_model(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email Verification')], default='email_verification', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
