# Generated by Django 5.2.7 on 2025-11-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userotp'),
        ('users', '0004_schedulednotification'),
    ]

    operations = [
    ]
